# Generated by Django 2.2.21 on 2021-05-30 16:01

import adm_request.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADMRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(db_index=True, unique=True, verbose_name='Номер претензии')),
                ('slug', models.SlugField(help_text='Название в url. Может содержать латинские буквы, подчеркивания, тире и цифры', max_length=200)),
                ('date', models.DateField(verbose_name='От')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'ADM запрос',
                'verbose_name_plural': 'ADM запросы',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='ConclusionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тип заклюяения',
                'verbose_name_plural': 'Типы заключений',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(help_text='Название в url. Может содержать латинские буквы, подчеркивания, тире и цифры', max_length=200)),
                ('file', models.FileField(upload_to=adm_request.models.Document.get_file_path)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('result', models.TextField(blank=True, null=True, verbose_name='Результат')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('adm_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm_request.ADMRequest', verbose_name='ADM-запрос')),
                ('documents', models.ManyToManyField(related_name='investigations', to='adm_request.Document', verbose_name='Документы')),
            ],
            options={
                'verbose_name': 'Расследование',
                'verbose_name_plural': 'Расследования',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='StoryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Введите описание', max_length=228, verbose_name='Описание')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_story', to='adm_request.Investigation')),
            ],
        ),
        migrations.CreateModel(
            name='Conclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер')),
                ('description', models.TextField(help_text='Введите описание сделанного заключения', verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('payoff_required', models.BooleanField()),
                ('conclusion_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm_request.ConclusionType', verbose_name='Тип заключения')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conclusion', to='adm_request.Document')),
            ],
            options={
                'verbose_name': 'Заключение',
                'verbose_name_plural': 'Заключения',
                'ordering': ('-updated',),
            },
        ),
        migrations.AddField(
            model_name='admrequest',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adm_request.Document', verbose_name='Файл'),
        ),
    ]
