# Generated by Django 2.2.21 on 2021-05-30 16:36

import adm_request.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_request', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(unique=True, upload_to=adm_request.models.Document.get_file_path),
        ),
    ]
