# Generated by Django 2.2.21 on 2021-05-31 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_request', '0003_auto_20210531_0302'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='Документ', max_length=300, verbose_name='Название'),
        ),
    ]
