# Generated by Django 2.2.21 on 2021-05-31 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_request', '0004_document_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='Документ', help_text='Если ', max_length=300, verbose_name='Название'),
        ),
    ]
