# Generated by Django 2.2.21 on 2021-05-31 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm_request', '0005_auto_20210531_0450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Причина обращения',
                'verbose_name_plural': 'Причина обращения',
                'ordering': ('-updated',),
            },
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, db_index=True, default='Документ', help_text='Можно не заполнять данное поле. Название документа будет создано автоматически', max_length=300, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='admrequest',
            name='reason',
            field=models.ForeignKey(help_text='Выберите причину обращения', null=True, on_delete=django.db.models.deletion.CASCADE, to='adm_request.Reason', verbose_name='Причина обращения'),
        ),
    ]
