# Generated by Django 2.2.21 on 2021-06-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm_request', '0006_auto_20210531_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admrequest',
            name='reason',
            field=models.CharField(choices=[('ER', 'Рассчёт суммы обмена билетов'), ('VR', 'Рассчёт суммы добровольных возвратов билетов'), ('FR', 'Рассчёт суммы вынужденных возвратов билетов')], default='ER', max_length=200, verbose_name='Причина обращения'),
        ),
    ]
